from django.urls import path
from django.urls import re_path
from django.views.generic import RedirectView
from .views import (
    HomeView,
    ServiceListView,
    DoctorDetailView,
    AboutView,
    DoctorListView,
    NewsListView,
    NewsDetailView,
    GlossaryListView,
    ContactsView,
    PrivacyPolicyView,
    VacancyListView,
    ListView,
    Review,
    ReviewCreateView,
    PromoCodeListView,
    TemplateView,
    CustomLoginView,
    CustomLogoutView,
    SignUpView,
    ClientDashboardView,
    DoctorDashboardView,
    LogoutView,
    role_based_redirect,
    UpdateProfileView,
    DeleteAccountView,
    BookAppointmentView,
    ServiceDetailView,
    CompleteAppointmentView,
    StatisticsView,
    set_timezone,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('services/', ServiceListView.as_view(), name='services'),

    re_path(r'^doctors/$', DoctorListView.as_view(), name='doctors'),
    re_path(r'^doctors/(?P<pk>\d+)/$', DoctorDetailView.as_view(), name='doctor-detail'),
    #path('doctors/', DoctorListView.as_view(), name='doctors'),
    #path('doctors/<int:pk>/', DoctorDetailView.as_view(), name='doctor-detail'),

    path('about/', AboutView.as_view(), name='about'), 
    path('news/', NewsListView.as_view(), name='news'),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news-detail'),
    path('glossary/', GlossaryListView.as_view(), name='glossary'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('privacy/', TemplateView.as_view(template_name='core/privacy_policy.html'), name='privacy-policy'),
    path('vacancies/', VacancyListView.as_view(), name='vacancies'),
    path('reviews/', ListView.as_view(model=Review, template_name='core/reviews.html'), name='reviews'),
    path('add-review/', ReviewCreateView.as_view(), name='add-review'),
    path('promocodes/', PromoCodeListView.as_view(), name='promocodes'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('dashboard/client/', ClientDashboardView.as_view(), name='client-dashboard'),
    path('dashboard/doctor/', DoctorDashboardView.as_view(), name='doctor-dashboard'),
    path('accounts/profile/', RedirectView.as_view(pattern_name='role-based-redirect')),
    path('dashboard/', role_based_redirect, name='role-based-redirect'),
    path('update-profile/', UpdateProfileView.as_view(), name='update-profile'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete-account'),
    path('update-profile/', UpdateProfileView.as_view(), name='update-profile'),
    path('service/<int:pk>/', ServiceDetailView.as_view(), name='service-detail'),
    path('service/<int:pk>/book/', BookAppointmentView.as_view(), name='book-appointment'),
    path('complete-appointment/<int:pk>/', CompleteAppointmentView.as_view(), name='complete-appointment'),
    path('vacancies/', VacancyListView.as_view(), name='vacancy-list'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('set-timezone/', set_timezone, name='set-timezone'),
]